sources:
    - name: PoolFactory
      handler:
          graphql:
              endpoint: ${NEXT_PUBLIC_POOLS_ENDPOINT}
    - name: Voter
      handler:
          graphql:
              endpoint: ${NEXT_PUBLIC_VOTER_ENDPOINT}

documents:
    - src/graphql/*.graphql
