sources:
  - name: PoolFactory
    handler:
      graphql:
        endpoint: ${NEXT_PUBLIC_POOLS_ENDPOINT}
  - name: Voter
    handler:
      graphql:
        endpoint: ${NEXT_PUBLIC_VOTER_ENDPOINT}
  - name: VotingEscrow
    handler:
      graphql:
        endpoint: ${NEXT_PUBLIC_ESCROW_ENDPOINT}

documents:
  - src/graphql/*.graphql
