import type { Metadata } from 'next';
import { Footer } from './components/Footer';
import { Header } from './components/Header';
import './globals.css';

export const metadata: Metadata = {
  title: 'Moniswap',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex min-h-svh flex-col bg-black font-minecraft text-white">
        <main className="flex-1">{children}</main>
        <Header />
        <Footer />
      </body>
    </html>
  );
}
