import { GoogleAnalytics } from '@next/third-parties/google';
import type { Metadata } from 'next';
import './globals.css';
import { Providers } from './providers';

export const metadata: Metadata = {
  title: 'Moniswap',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black font-minecraft text-white">
        <Providers>
          <main className="flex-1">{children}</main>
        </Providers>
      </body>
      <GoogleAnalytics gaId="G-HFEN1RRYYP" />
    </html>
  );
}
